parameters:
#    poblacion.example.class: Sp\PoblacionBundle\Example

services:
#    poblacion.example:
#        class: %poblacion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
