parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: base
    database_user: root
    database_password: p43012
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 110526b3c68ba37eb78f6e6b747f64ba7b98fab6
    database_path: null
