pagina_estatica:
    pattern: /sitio/{pagina}/
    defaults: { _controller: FrondBundle:Sitio:estatica }
frond:
    resource: "@FrondBundle/Resources/config/routing.yml"
    prefix:   /
zona:
    resource: "@ZonaBundle/Resources/config/routing.yml"
    prefix:   /

poblacion:
    resource: "@PoblacionBundle/Resources/config/routing.yml"
    prefix:   /

provincia:
    resource: "@ProvinciaBundle/Resources/config/routing.yml"
    prefix:   /

pais:
    resource: "@PaisBundle/Resources/config/routing.yml"
    prefix:   /
# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
